/* CRIS IDP registers

THIS FILE IS MACHINE GENERATED WITH CGEN.

Copyright 1996-2010 Free Software Foundation, Inc.

This file is part of the GNU Binutils and/or GDB, the GNU debugger.

   This file is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 3, or (at your option)
   any later version.

   It is distributed in the hope that it will be useful, but WITHOUT
   ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
   or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
   License for more details.

   You should have received a copy of the GNU General Public License along
   with this program; if not, write to the Free Software Foundation, Inc.,
   51 Franklin Street - Fifth Floor, Boston, MA 02110-1301, USA.

*/

/* This file is only to be included by whoever defines LPH! */

static const char *const RegNames[] =
{
  "h-v32-v32", 
  "h-pc", 
  "h-gr-0", 
  "h-gr-1", 
  "h-gr-2", 
  "h-gr-3", 
  "h-gr-4", 
  "h-gr-5", 
  "h-gr-6", 
  "h-gr-7", 
  "h-gr-8", 
  "h-gr-9", 
  "h-gr-10", 
  "h-gr-11", 
  "h-gr-12", 
  "h-gr-13", 
  "h-gr-14", 
  "h-gr-15", 
  "R0", 
  "R1", 
  "R2", 
  "R3", 
  "R4", 
  "R5", 
  "R6", 
  "R7", 
  "R8", 
  "R9", 
  "R10", 
  "R11", 
  "R12", 
  "R13", 
  "SP", 
  "ACR", 
  "h-raw-gr-acr-0", 
  "h-raw-gr-acr-1", 
  "h-raw-gr-acr-2", 
  "h-raw-gr-acr-3", 
  "h-raw-gr-acr-4", 
  "h-raw-gr-acr-5", 
  "h-raw-gr-acr-6", 
  "h-raw-gr-acr-7", 
  "h-raw-gr-acr-8", 
  "h-raw-gr-acr-9", 
  "h-raw-gr-acr-10", 
  "h-raw-gr-acr-11", 
  "h-raw-gr-acr-12", 
  "h-raw-gr-acr-13", 
  "h-raw-gr-acr-14", 
  "h-raw-gr-acr-15", 
  "h-sr-0", 
  "h-sr-1", 
  "h-sr-2", 
  "h-sr-3", 
  "h-sr-4", 
  "h-sr-5", 
  "h-sr-6", 
  "h-sr-7", 
  "h-sr-8", 
  "h-sr-9", 
  "h-sr-10", 
  "h-sr-11", 
  "h-sr-12", 
  "h-sr-13", 
  "h-sr-14", 
  "h-sr-15", 
  "BZ", 
  "VR", 
  "PID", 
  "SRS", 
  "WZ", 
  "EXS", 
  "EDA", 
  "MOF", 
  "DZ", 
  "EBP", 
  "ERP", 
  "SRP", 
  "NRP", 
  "CCS", 
  "USP", 
  "SPC", 
  "h-supr-0", 
  "h-supr-1", 
  "h-supr-2", 
  "h-supr-3", 
  "h-supr-4", 
  "h-supr-5", 
  "h-supr-6", 
  "h-supr-7", 
  "h-supr-8", 
  "h-supr-9", 
  "h-supr-10", 
  "h-supr-11", 
  "h-supr-12", 
  "h-supr-13", 
  "h-supr-14", 
  "h-supr-15", 
  "h-cbit", 
  "h-cbit-move", 
  "h-cbit-move-v32", 
  "h-vbit", 
  "h-vbit-move", 
  "h-vbit-move-v32", 
  "h-zbit", 
  "h-zbit-move", 
  "h-zbit-move-v32", 
  "h-nbit", 
  "h-nbit-move", 
  "h-nbit-move-v32", 
  "h-xbit", 
  "h-ibit", 
  "h-pbit", 
  "h-rbit", 
  "h-ubit", 
  "h-gbit", 
  "h-kernel-sp", 
  "h-ubit-v32", 
  "h-ibit-v32", 
  "h-mbit", 
  "h-qbit", 
  "h-sbit", 
  "h-insn-prefixed-p", 
  "h-insn-prefixed-p-v32", 
  "h-prefixreg-v32", 
};
